field_application/field_application/account/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from field_application.account.permission import check_user_pk, check_perms
from field_application.account.views import org_manage, disable_org
from field_application.account.views import manager_reset_password
from field_application.account.views import SignOutView, SignInView 
from field_application.account.views import SignUpView, ResetPasswordView
from field_application.account.views import EditProfile, Profile


urlpatterns = patterns(
    '',
    url(r'^signin/$', SignInView.as_view(), name='signin'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signout/$', SignOutView.as_view(), name='signout'),
    url(r'^reset_password/$', ResetPasswordView.as_view(), 
        name='reset_password'),
    url(r'^profile/(?P<pk>\d+)/$',
        check_user_pk(Profile.as_view()), name='profile'),
    url(r'^edit_profile/(?P<pk>\d+)/$', 
        check_user_pk(EditProfile.as_view()), name='edit_profile'),

    # only manager can use
    url(r'^org_manage/$',
        check_perms('account.manager', message=u'无管理权限') \
                (org_manage), name='org_manage'),
    url(r'^disable_org/$',
        check_perms('account.manager', message=u'无管理权限') \
            (disable_org), name='disable_org'),
    # this is used by manager to set password to 123456
    url(r'^manager_reset_password/$', manager_reset_password,
        name='manager_reset_password'),
 )

field_application/field_application/document/urls.py
from django.conf.urls import url, patterns
from django.conf import settings
from django.conf.urls.static import static
from field_application.document.views import UploadFileView,delete,index

urlpatterns = patterns('',
    url(r'^$',  index, name='index'),
    url(r'^delete/$', delete, name='delete'),
    url(r'^modify/$', UploadFileView.as_view(), name='upload'),

)

field_application/field_application/meeting_room/urls.py
from django.conf.urls import url, patterns

from field_application.meeting_room.views import display_table
from field_application.meeting_room.views import ListAppView 
from field_application.meeting_room.views import ApplyMeetingRoomView
from field_application.meeting_room.views import get_detail, delete
from field_application.meeting_room.views import ModifyView
from field_application.meeting_room.views import ManageView 
from field_application.meeting_room.views import manager_approve 
from field_application.meeting_room.views import conflict_for_form

urlpatterns = patterns(
    '',
    url(r'^apply/$', ApplyMeetingRoomView.as_view(), name='apply'),
    url(r'^table/$', display_table, name='table'),
    url(r'^list/$', ListAppView.as_view(), name='list'),
    url(r'^manage/$', ManageView.as_view(), name='manage'),
    url(r'^get_detail/$', get_detail, name='get_detail'),
    url(r'^modify/$', ModifyView.as_view(), name='modify'),
    url(r'^delete/$', delete, name='delete'),
    url(r'^manager_approve/$', manager_approve, name='manager_approve'),

    url(r'^conflict_for_form/$', conflict_for_form,
        name='conflict_for_form'),
 )

field_application/field_application/urls.py
import os

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin

from field_application import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html'),
               name='home'),
    url(r'^deny/$', TemplateView.as_view(template_name='deny.html'),
               name='deny'),
    url(r'^account/', include('field_application.account.urls',
                              namespace='account')),
    url(r'^student_activity_center/',
        include('field_application.student_activity_center.urls',
                namespace='student_activity_center')),
    url(r'^meeting_room/', include('field_application.meeting_room.urls',
                                   namespace='meeting_room')),
    url(r'^exhibit/',
        include('field_application.campus_field.exhibit.urls',
                                   namespace='exhibit')),
    url(r'^publicity/',
        include('field_application.campus_field.publicity.urls',
                                   namespace='publicity')),
    url(r'^integrated_service/',
    include('field_application.integrated_service.urls',
                               namespace='integrated_service')),
    url(r'^document/',
        include('field_application.document.urls',
                                   namespace='document')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # not used now
   #url(r'^south_stadium/', include('field_application.south_stadium.urls',
    #                                namespace='south_stadium')),
)

# serve media file when using developing server
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^uploaded-file/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}),
        )

field_application/field_application/account/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms import HiddenInput

from field_application.account.models import Organization


BELONG_TO_CHOICES = (
    ('其它','其它'),
    ('社团联合会','社团联合会'),
    ('校学生会','校学生会'),
    )

class SignInForm(AuthenticationForm):

    # 由于这部分django没有翻译，所以直接重写错误信息
    # 注意这不是文档中有说明的接口，当前版本是1.5.1，可能会在新版本失效
    error_messages = {
        'invalid_login': u'请输入正确的组织名和密码',
        'inactive': u'该帐号处于停用状态',
    }

    username = forms.ModelChoiceField(queryset=Organization.objects.all(),
                                      empty_label=u'')

    def clean_username(self):
        ''' change Organization.chinese_name to User.username '''
        org = Organization.objects.get(
                chinese_name=self.cleaned_data['username'])
        if org.is_banned and not org.user.has_perm('account.manager'):
            raise forms.ValidationError(u'该用户已被禁止使用')
        return org.user.username

class SignUpForm(UserCreationForm):

    chinese_name = forms.CharField(max_length=30)
    org_in_charge = forms.CharField(max_length=30)
    tutor = forms.CharField(max_length=20)
    tutor_contact_infor = forms.CharField(max_length=30)
    director = forms.CharField(max_length=20)
    director_contact_infor = forms.CharField(max_length=30)
    belong_to = forms.ChoiceField(choices=BELONG_TO_CHOICES)

    def clean_chinese_name(self):
        chinese_name = self.cleaned_data.get('chinese_name')
        if Organization.objects.filter(chinese_name=chinese_name).exists():
            raise forms.ValidationError(u'该中文名已被注册')
        return chinese_name

    # force model to save
    def save(self):
        new_user = super(SignUpForm, self).save()
        org = Organization.objects.create(
            user=new_user,
            chinese_name = self.cleaned_data['chinese_name'],
            org_in_charge=self.cleaned_data['org_in_charge'],
            tutor=self.cleaned_data['tutor'],
            tutor_contact_infor=self.cleaned_data['tutor_contact_infor'],
            director=self.cleaned_data['director'],
            director_contact_infor=self.cleaned_data['director_contact_infor'],
            belong_to=self.cleaned_data['belong_to'])
        org.save()
        return org


class EditForm(forms.ModelForm):
    belong_to = forms.ChoiceField(choices=BELONG_TO_CHOICES)
    class Meta:
        model = Organization
        exclude = ('chinese_name', 'user', 'is_banned')


field_application/field_application/document/forms.py
from django import forms
from field_application.document.models import Document 

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document

field_application/field_application/integrated_service/forms.py
#-*- coding: utf-8 -*-
from datetime import timedelta, datetime

from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.forms import Textarea, RadioSelect
from django.forms import CheckboxSelectMultiple 

from field_application.integrated_service.models import InteServiceApplication 


class InteServiceApplicationForm(forms.ModelForm):
    place = forms.ChoiceField(choices=InteServiceApplication.PLACE,
                              widget=RadioSelect())
    class Meta:
        model = InteServiceApplication
        exclude = ['organization', 'approved', 'application_time']
        widgets = {
            'date': SelectDateWidget(),
            'summary': Textarea(),
            'remarks': Textarea(),
        }

    def clean_date(self):
        date = self.cleaned_data.get('date')
        now = datetime.now().date()
        if date < now:
            raise forms.ValidationError(u'所填日期已过')
        if date >= now + timedelta(days=14):
            raise forms.ValidationError(
                    u'申请的场地使用时间距离现在不能超过14天')
        return date

    def clean(self):
        if 'time' not in self.cleaned_data or \
                'date' not in self.cleaned_data or \
                'place' not in self.cleaned_data:
            return super(InteServiceApplicationForm, self).clean()
        super(InteServiceApplicationForm, self).clean()

        for time in self.cleaned_data['time']:
            if InteServiceApplication.objects.filter(
                    place=self.cleaned_data.get('place'),
                    date=self.cleaned_data.get('date'),
                    time__contains=time,
                    approved=True).exists():
                msg = time + u'已有人申请'
                self._errors['time'] = self.error_class([msg])
                raise forms.ValidationError(
                    u'您的申请与别人有冲突，请检查')
        return self.cleaned_data

field_application/field_application/utils/forms.py
#-*- coding: utf-8 -*-
from django import forms

class SearchForm(forms.Form):

    SEARCH_CHOICES = (
        ('org', u'申请组织'),
        ('title', u'活动标题'),
        ('place', u'活动地点'),
    )

    APPROVED_CHOICES = (
        ('all', u'全部'),
        ('yes', u'已批准'),
        ('no', u'未批准'),
    )

    search_type = forms.ChoiceField(choices=SEARCH_CHOICES)
    search_value = forms.CharField(max_length=40, required=False)
    approved = forms.ChoiceField(choices=APPROVED_CHOICES)

field_application/field_application/account/views.py
#-*- coding: utf-8 -*-
import logging

from django.views.generic import View
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView, ListView

from field_application.account.permission import guest_or_redirect
from field_application.account.permission import check_perms 
from field_application.account.forms import SignUpForm, SignInForm
from field_application.account.models import UserActivityLog, get_client_ip
from field_application.account.models import Organization
from field_application.account.forms import EditForm


logger = logging.getLogger(__name__)


class SignInView(View):

    @method_decorator(guest_or_redirect)
    def get(self, request):
        return render(request, 'account/sign-in.html',
                      {'form': SignInForm(),
                       'next': request.GET.get('next')})

    @method_decorator(guest_or_redirect)
    def post(self, request):
        form = SignInForm(data=request.POST)
        if not form.is_valid():
            return render(request, 'account/sign-in.html', {'form': form})

        user = form.get_user()
        if not hasattr(user, 'organization'):
            error_message = '''some one is using a user who don't have
                               corresponding organization(super user
                               for example) to apply. Please check it.'''
            logger.error(error_message)
            form.errors['__all__'] = form.error_class(
                ["user doesn't has corresponding org"]
            )
            return render(request, 'account/sign-in.html', {'form': form})

        login(request, user)
        UserActivityLog.objects.create(user=user,
                                       ip_address=get_client_ip(request),
                                       behavior="Login")
        if request.GET.get('next'):
            return HttpResponseRedirect(request.GET.get('next'))
        else:
            return HttpResponseRedirect(reverse('home'))


class SignUpView(View):

    @method_decorator(guest_or_redirect)
    def get(self, request):
        return render(request, 'account/sign-up.html',
                      {'form': SignUpForm()})

    @method_decorator(guest_or_redirect)
    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('account:signin'))

        return render(request, 'account/sign-up.html', {'form': form})


class SignOutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('home'))


class ResetPasswordView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'account/reset-password.html',
                      {'form': PasswordChangeForm(user=request.user)})

    @method_decorator(login_required)
    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if not form.is_valid():
            return render(request, 'account/reset-password.html',
                          {'form': form})
        form.save()
        UserActivityLog.objects.create(user=request.user,
                                       ip_address=get_client_ip(request),
                                       behavior=u"修改密码")
        return HttpResponseRedirect(reverse('home'))


class EditProfile(UpdateView):
    model = Organization
    form_class = EditForm
    template_name = 'account/edit-profile.html'
    success_url = '/'


class Profile(DetailView):
    model = Organization
    fields = ['chinese_name', 'org_in_charge',
              'tutor','tutor_contact_infor',
              'director', 'director_contact_infor',
              'belong_to', 'is_banned']
    template_name = 'account/profile.html'
    context_object_name = 'organization'


def org_manage(request):
    orgs = Organization.objects.filter(
        user__is_active=True).order_by('-pk')
    return render(request, 'account/org-manage.html',
            {'list': orgs})


@permission_required('account.manager')
def disable_org(request):
    org_id = request.GET.get('id')
    org = get_object_or_404(Organization, id=org_id)
    org.is_banned = not org.is_banned
    org.save()
    return HttpResponseRedirect(reverse('account:org_manage'))


@check_perms('account.manager', message='无管理权限')
def manager_reset_password(request):
    org_id = request.GET.get('id')
    org = get_object_or_404(Organization, id=org_id)
    org.user.set_password('123456')
    org.user.save()
    return HttpResponseRedirect(reverse('account:org_manage'))

field_application/field_application/document/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from field_application.document.models import Document
from field_application.document.forms import DocumentForm
from field_application.account.permission import check_perms

def index(request):
    doc_list = Document.objects.all()
    return render(request, 'document/index.html', {'doc_list':doc_list})

class UploadFileView(View):
    @method_decorator(login_required)
    @method_decorator(check_perms('account.manager', u'无管理权限'))
    def post(self, request):
        doc_list = Document.objects.all()
        form = DocumentForm(request.POST, request.FILES)
        if not form.is_valid():
            return render(request, 'document/document.html', {'form':form, 'doc_list':doc_list})
        form.save()
        return HttpResponseRedirect(reverse('document:upload'))

    @method_decorator(login_required)
    @method_decorator(check_perms('account.manager', u'无管理权限'))
    def get(self, request):
        form = DocumentForm()
        doc_list = Document.objects.all()
        return render(request, 'document/document.html', {'form':form, 'doc_list':doc_list})

@check_perms('account.manager', u'无管理权限')
def delete(request):
    doc_id = request.GET.get('id')
    doc = get_object_or_404(Document, id=doc_id)
    doc.delete()
    return HttpResponseRedirect(reverse('document:upload'))

field_application/field_application/templates/apply_base.html
{% extends 'base.html' %}

{% block base_htmlhead %}
    {% load html_tools %}
    {{ 'apply/base.css' | as_css }}
    {{ 'apply/form_main.css' | as_css }}
    {% block htmlhead %}{% endblock %}
{% endblock %}

{% block main_container %}
    {% block main_content %}
    {% endblock %}
{% endblock %}

field_application/field_application/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="深圳大学,深大,荔园,学子天地,场地申请,南区体育馆,运动广场,申请表">
    <meta name="description" content="深圳大学资讯传媒社区, 荔园信息聚集平台">
    <title>{% block htmltitle %} {% endblock %}</title>
    {% load html_tools %}
    {{ 'base.css' | as_css }}
    {{ 'materialize.min.css' | as_css }}
	{{ 'jQuery/jquery-3.2.1.min.js' | as_js }}
	{{ 'materialize.min.js' | as_js}}
    {% block base_htmlhead %}{% endblock %}
</head>
<body>
    <nav class="nav-extended blue">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="nav-wrapper">
                        <span class="ostitle"><a href="/"><img src="/static/images/szu_logo.png" class="logo"></a></span>
                        <ul class="right hide-on-med-and-down">
							{% if user.is_authenticated %}
							<li>{{ user.organization.chinese_name }}</li>
							<li><a href="{% url 'account:signout' %}">注销</a></li>
                            <li><a href="{% url 'account:reset_password' %}">修改密码</a></li>
							<li><a href="{% url 'account:edit_profile' user.pk %}">编辑资料</a></li>
                            <li><a href="{% url 'account:profile' user.pk %}">查看资料</a></li>
							{% if perms.account.manager %}
							<li><a href="{% url 'account:org_manage' %}">管理组织</a></li>
							{% endif %}
							{% else %}
                            <li><a href="{% url 'account:signin' %}">登录</a></li>
                            <li><a href="{% url 'account:signup' %}">注册</a></li>
							{% endif %}
							<li><a href="{% url 'document:index' %}">表格下载</a></li>
                        </ul>
                        {% block top_title %}<h1 class="gdtitle">场地申请系统</h1>{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col s12">
            <div class="card-panel">
                <a href="/">【返回场地申请主页】</a>
                <a href="../manage/">【管理场地申请】</a>
                <a href="../table/">【查看场地申请情况】</a>
            </div>
            </div>
        <div class="row">
            <div class="col s12">
                {% block main_container %}
                {% endblock %}
            </div>
        </div>
        </div>
    </div>

    <footer class="page-footer blue">
        <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">网站有问题？</h5>
                <p class="grey-text text-lighten-4" style="text-align:left;">如果你发现网站有任何问题,请立刻联系我们(陈同学,qq649743466)，或者在我们的办公时间（周一到周五第3~4、5~6、7~8节课）到我们的办公室：西南综合服务楼一楼112号室 告知我们。<del>就算没人在你也可以贴个便利贴神马的</del></p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">关注学子天地公众号</h5>
                <img src="/static/images/stu_barcode.jpg">
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            ©2017 StuCampus·SZU ALL RIGHTS RESERVED.
            <a class="grey-text text-lighten-4 right" href="http://stu.szu.edu.cn/">版权所有© 深圳大学·学子天地 技术开发部</a>
            </div>
          </div>
    </footer>
</body>
</html>

field_application/field_application/templates/deny.html
{% extends 'account/account_base.html' %}

{% block htmltitle %}管理{% endblock %}

{% block base_htmlhead %}
    {% load html_tools %}
    {{ 'account/account.css' | as_css }}
{% endblock %}

{% block main_container %}
<h1 class="has_margin" style="color: #ff0000; text-align: center;">
    {{ message }}
</h1>
{% endblock %}

field_application/field_application/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<meta http-equiv="Content-Language" content="zh-CN">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="深圳大学,深大,荔园,学子天地,场地申请,首页">
    <meta name="description" content="深圳大学资讯传媒社区, 荔园信息聚集平台">
    <title>场地申请首页</title>
	{% load html_tools %}
    {{ 'main.css' | as_css }}
	{{ 'materialize.min.css' | as_css }}
	{{ 'jQuery/jquery-3.2.1.min.js' | as_js }}
	{{ 'materialize.min.js' | as_js}}
</head>
<body>
	<nav class="nav-extended blue">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div class="nav-wrapper">
                        <span class="ostitle"><a href="/"><img src="/static/images/szu_logo.png" class="logo"></a></span>
                        <ul class="right hide-on-med-and-down">
							{% if user.is_authenticated %}
							<li>{{ user.organization.chinese_name }}</li>
							<li><a href="{% url 'account:signout' %}">注销</a></li>
                            <li><a href="{% url 'account:reset_password' %}">修改密码</a></li>
							<li><a href="{% url 'account:edit_profile' user.pk %}">编辑资料</a></li>
                            <li><a href="{% url 'account:profile' user.pk %}">查看资料</a></li>
							{% if perms.account.manager %}
							<li><a href="{% url 'account:org_manage' %}">管理组织</a></li>
							{% endif %}
							{% else %}
                            <li><a href="{% url 'account:signin' %}">登录</a></li>
                            <li><a href="{% url 'account:signup' %}">注册</a></li>
							{% endif %}
							<li><a href="{% url 'document:index' %}">表格下载</a></li>
                        </ul>
                        <h1 class="gdtitle">场地申请系统</h1>
                    </div>
                </div>
            </div>
        </div>
    </nav>

	<div class="container">
		<div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <h5><b>申请场地前请务必仔细阅读<a href="/static/images/rules.html">深圳大学学生活动场地申请流程</a></b></h5>
                </div>
            </div>
        </div>  
        <div class="row">
			<h5>可供申请的场地种类</h5>
            <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                <span class="card-title">西南综合服务楼</span>
                </div>
                <div class="card-action">
                <a href="{% url 'integrated_service:table' %}">查看申请情况</a>
                <a href="{% url 'integrated_service:apply' %}">在线申请</a>
                </div>
            </div>
            </div>

            <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                <span class="card-title">学生活动中心</span>
                </div>
                <div class="card-action">
                <a href="{% url 'student_activity_center:table' %}">查看申请情况</a>
                <a href="{% url 'student_activity_center:apply' %}">在线申请</a>
                </div>
            </div>
            </div>

            <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                <span class="card-title">校园展览场地</span>
                </div>
                <div class="card-action">
                <a href="{% url 'exhibit:table' %}">查看申请情况</a>
                <a href="{% url 'exhibit:apply' %}">在线申请</a>
                </div>
            </div>
            </div>

			<div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                <span class="card-title">校园露天场地</span>
                </div>
                <div class="card-action">
                <a href="{% url 'publicity:table' %}">查看申请情况</a>
                <a href="{% url 'publicity:apply' %}">在线申请</a>
                </div>
            </div>
            </div>

			<div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                <span class="card-title">石头坞会议室</span>
                </div>
                <div class="card-action">
                <a href="{% url 'meeting_room:table' %}">查看申请情况</a>
                <a href="{% url 'meeting_room:apply' %}">在线申请</a>
                </div>
            </div>
            </div>
        </div>

    </div>


    <footer class="page-footer blue">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">网站有问题？</h5>
                <p class="grey-text text-lighten-4" style="text-align:left;">如果你发现网站有任何问题,请立刻联系我们(陈同学,qq649743466)，或者在我们的办公时间（周一到周五第3~4、5~6、7~8节课）到我们的办公室：西南综合服务楼一楼112号室 告知我们。</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">关注学子天地公众号</h5>
                <img src="/static/images/stu_barcode.jpg">
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            ©2017 StuCampus·SZU ALL RIGHTS RESERVED.
            <a class="grey-text text-lighten-4 right" href="http://stu.szu.edu.cn/">版权所有© 深圳大学·学子天地 技术开发部</a>
            </div>
          </div>
    </footer>
</body>
</html>



field_application/field_application/templates/list.html
{% extends 'list_base.html' %}

{% block htmltitle %}{{ title }}文字版{% endblock %}

{% block top_title %}<h1>{{ title }}</h1>{% endblock %}

{% block main_content %}
    <div class="search">
        <form action="" method="post">
            <a href="."><input type="button" value="显示全部" /></a>
            {% csrf_token %}

            {{ form.search_type }}
            <span class="error">
            {% for error in form.search_type.errors %}
                {{ error }}&nbsp;
            {% endfor %}
            </span>

            {{ form.search_value }}
            <span class="error">
            {% for error in form.search_value.errors %}
                {{ error }}&nbsp;
            {% endfor %}
            </span>

            {{ form.approved }}
            <span class="error">
            {% for error in form.approved.errors %}
                {{ error }}&nbsp;
            {% endfor %}
            </span>

            <input type="submit" value="提交" />
        </form>
    </div>
    
    <table class="table">
        <tr>
            <td style="min-width:100px">申请组织</td>
            <td style="min-width:100px">活动主题</td>
            <td style="min-width:150px">使用场地</td>
            <td style="width:95px">使用日期</td>
            <td style="min-width:100px">使用时间</td>
            <td style="width:90px">申请时间</td>
            <td style="width:70px">是否审批</td>
        </tr>
        {% for app in page %}
        <tr class="app">
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{{ app.organization }}</td>
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{{ app.activity }}</td> 
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{% for place in app.place %} {{ place }} {% endfor %}</td>
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{{ app.date }}</td>
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{% for time in app.time %} {{ time }} {% endfor %}</td>
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">{{ app.application_time | date:"Y年n月d日G时i分" }}</td>
            <td onclick="javascript:showAppForm({{ app.id }}, plc)">
                {% if app.approved %}
                    <span style="color: #ff0000;">已批准</span>
                {% else %}
                    未批准
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include 'paginator.html' with page=page %}
{% endblock %}

field_application/field_application/templates/list_base.html
{% extends 'base.html' %}

{% block base_htmlhead %}
    {% load html_tools %}
    {{ 'list/list.css' | as_css }}

    {{ 'artDialog/v4/artDialog.js'    | as_js  }}
    {{ 'artDialog/v4/skins/opera.css' | as_css }}
    {{ 'artDialog/popupBox.css'       | as_css }}

    {{ 'popupBox.js'  | as_js  }}
    <script>
        var plc = location.pathname.split('/')[1];
    </script>
    {% block htmlhead %}{% endblock %}
{% endblock %}

{% block main_container %}
    {% block main_content %}
    {% endblock %}
{% endblock %}

field_application/field_application/templates/paginator.html
<div class="paginator page">
    [第{{ page.number }}页/共{{ page.paginator.num_pages }}页/共{{ page.paginator.count }}项] 
    <span class="num">
        <a href="?page=1">首页</a>
    </span>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" class="previous">上一页</a>
    {% endif %}
    {% if page.has_next %}
        <a class="next" href="?page={{ page.next_page_number }}">下一页</a>
    {% endif %}
    <span class="num">
        <a href="?page={{ page.paginator.num_pages }}">尾页</a>
    </span>
</div>